# Generated by Django 3.2.6 on 2022-06-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sms_key_value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_id', models.CharField(max_length=50)),
                ('message_key', models.CharField(max_length=200)),
                ('message_value', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='sms_que',
            name='app_data_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='sms_que',
            name='app_user_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
