# Generated by Django 3.2.6 on 2022-06-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_auto_20220614_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms_application_settings',
            name='api_secret',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sms_application_settings',
            name='sms_api',
            field=models.CharField(choices=[('1', 'ADN SMS'), ('2', 'sManager')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='sms_sent',
            name='sms_uid',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sms_que',
            name='template_type',
            field=models.CharField(choices=[('1', 'ADN SMS'), ('2', 'sManager')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='sms_sent',
            name='template_type',
            field=models.CharField(choices=[('1', 'ADN SMS'), ('2', 'sManager')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='sms_template',
            name='template_type',
            field=models.CharField(choices=[('1', 'ADN SMS'), ('2', 'sManager')], default='', max_length=10),
        ),
    ]
