# Generated by Django 3.2.6 on 2022-06-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_auto_20220614_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms_que',
            name='template_type',
            field=models.CharField(choices=[('', '----------------'), ('1', 'Sales Invoice'), ('2', 'Purchase Bill Payment'), ('3', 'Member Admission'), ('4', 'Deposit Receive'), ('5', 'Deposit Payment'), ('6', 'Loan Disbursement'), ('7', 'Loan Installment Receive'), ('8', 'Loan Installment Due'), ('9', 'Loan Installment Overdue'), ('10', 'Loan Installment Receive From Deposit'), ('20', 'Share Receive'), ('21', 'Share Payment')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='sms_sent',
            name='template_type',
            field=models.CharField(choices=[('', '----------------'), ('1', 'Sales Invoice'), ('2', 'Purchase Bill Payment'), ('3', 'Member Admission'), ('4', 'Deposit Receive'), ('5', 'Deposit Payment'), ('6', 'Loan Disbursement'), ('7', 'Loan Installment Receive'), ('8', 'Loan Installment Due'), ('9', 'Loan Installment Overdue'), ('10', 'Loan Installment Receive From Deposit'), ('20', 'Share Receive'), ('21', 'Share Payment')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='sms_template',
            name='template_type',
            field=models.CharField(choices=[('', '----------------'), ('1', 'Sales Invoice'), ('2', 'Purchase Bill Payment'), ('3', 'Member Admission'), ('4', 'Deposit Receive'), ('5', 'Deposit Payment'), ('6', 'Loan Disbursement'), ('7', 'Loan Installment Receive'), ('8', 'Loan Installment Due'), ('9', 'Loan Installment Overdue'), ('10', 'Loan Installment Receive From Deposit'), ('20', 'Share Receive'), ('21', 'Share Payment')], default='', max_length=10),
        ),
    ]
