# Generated by Django 3.2.6 on 2022-08-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0006_auto_20220622_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms_application_settings',
            name='sms_api',
            field=models.CharField(choices=[('1', 'ADN SMS'), ('2', 'sManager'), ('3', 'REVE')], default='', max_length=10),
        ),
    ]
