# Generated by Django 3.2.6 on 2022-11-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0007_alter_sms_application_settings_sms_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms_application_settings',
            name='balance_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sms_application_settings',
            name='client_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sms_que',
            name='template_type',
            field=models.CharField(choices=[('', '----------------'), ('1', 'Sales Invoice'), ('2', 'Purchase Bill Payment'), ('3', 'Member Admission'), ('4', 'Deposit Receive'), ('5', 'Deposit Payment'), ('6', 'Loan Disbursement'), ('7', 'Loan Installment Receive'), ('8', 'Loan Installment Due'), ('9', 'Loan Installment Overdue'), ('10', 'Loan Installment Receive From Deposit'), ('11', 'FDR Open'), ('12', 'DPS Open'), ('13', 'FDR Profit Transfer'), ('14', 'Deposit Profit Transfer'), ('15', 'FDR Closing'), ('16', 'DPS Closing'), ('17', 'Savings Open'), ('18', 'Savings Closing'), ('20', 'Share Receive'), ('21', 'Share Payment'), ('22', 'DPS Receive'), ('23', 'DPS Payment'), ('00', 'Manual SMS Send')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='sms_sent',
            name='template_type',
            field=models.CharField(choices=[('', '----------------'), ('1', 'Sales Invoice'), ('2', 'Purchase Bill Payment'), ('3', 'Member Admission'), ('4', 'Deposit Receive'), ('5', 'Deposit Payment'), ('6', 'Loan Disbursement'), ('7', 'Loan Installment Receive'), ('8', 'Loan Installment Due'), ('9', 'Loan Installment Overdue'), ('10', 'Loan Installment Receive From Deposit'), ('11', 'FDR Open'), ('12', 'DPS Open'), ('13', 'FDR Profit Transfer'), ('14', 'Deposit Profit Transfer'), ('15', 'FDR Closing'), ('16', 'DPS Closing'), ('17', 'Savings Open'), ('18', 'Savings Closing'), ('20', 'Share Receive'), ('21', 'Share Payment'), ('22', 'DPS Receive'), ('23', 'DPS Payment'), ('00', 'Manual SMS Send')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='sms_template',
            name='template_type',
            field=models.CharField(choices=[('', '----------------'), ('1', 'Sales Invoice'), ('2', 'Purchase Bill Payment'), ('3', 'Member Admission'), ('4', 'Deposit Receive'), ('5', 'Deposit Payment'), ('6', 'Loan Disbursement'), ('7', 'Loan Installment Receive'), ('8', 'Loan Installment Due'), ('9', 'Loan Installment Overdue'), ('10', 'Loan Installment Receive From Deposit'), ('11', 'FDR Open'), ('12', 'DPS Open'), ('13', 'FDR Profit Transfer'), ('14', 'Deposit Profit Transfer'), ('15', 'FDR Closing'), ('16', 'DPS Closing'), ('17', 'Savings Open'), ('18', 'Savings Closing'), ('20', 'Share Receive'), ('21', 'Share Payment'), ('22', 'DPS Receive'), ('23', 'DPS Payment'), ('00', 'Manual SMS Send')], default='', max_length=10),
        ),
    ]
